import numpy as np
import time
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from mpi4py import MPI
from mpi4py.futures import MPIPoolExecutor, as_completed

# =================================================================
# 2. GLOBAL DATA SETUP (GENERATED BY ALL PROCESSES)
# The data is generated here so all MPI processes (master and workers) 
# have the same static dataset available in their memory without 
# requiring communication for every task.
# =================================================================
X, y = make_classification(
    n_samples=100000,
    n_features=200,
    n_informative=10,
    n_redundant=10,
    n_repeated=0,
    n_classes=2,
    n_clusters_per_class=2,
    class_sep=1.2,
    flip_y=0.08,
    weights=[0.5, 0.5],
    random_state=42, # CRUCIAL: Ensures all processes generate identical data
)

X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# Scale features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)

# -------------------------------------------------------------
# 1. Worker function for a single HPO trial
#    Data is now accessed from the module's global scope.
# -------------------------------------------------------------
def train_and_evaluate(C, trial_id):
    """
    Trains a Logistic Regression model for a given C and evaluates it.
    Data is accessed globally. Only C and trial_id are passed as arguments.
    """
    
    # Access the globally defined data arrays
    global X_train, y_train, X_val, y_val
    
    # Initialize the model with L1 penalty and C
    clf = LogisticRegression(
        C=C,
        penalty="l1",
        solver="saga",      # Supports L1 on large, high-dim problems
        max_iter=3000,
        n_jobs=1,           # Use 1 job per process to avoid oversubscription
        random_state=42
    )

    # Train the model
    clf.fit(X_train, y_train)
    
    # Predict and evaluate
    y_pred = clf.predict(X_val)
    acc = accuracy_score(y_val, y_pred)
    
    # Return all results needed for tracking
    return C, acc, trial_id


if __name__ == "__main__":
    
    # Initialize rank and ensure master is identified correctly
    MASTER_RANK = 0
    rank = MPI.COMM_WORLD.Get_rank()

    # Only the master process proceeds with submission and result processing
    if rank == MASTER_RANK:
        
        # -----------------------------
        # 3. Parallel HPO setup
        # -----------------------------
        rng = np.random.default_rng(0)
        n_trials = 32
        results = []
        
        # Generate the C values once
        C_values = [10 ** rng.uniform(-5, -1) for _ in range(n_trials)]
        
        all_futures = {}
        
        # --- Timing Start ---
        start = time.time()
    
    # Use MPIPoolExecutor. This block manages communication between master and workers.
    with MPIPoolExecutor() as executor:
        
        # The master process (rank 0) handles submission and collection
        if rank == MASTER_RANK:
            
            # Submit all tasks to the executor
            for i, C in enumerate(C_values):
                # Submit the task, passing ONLY the small parameters C and i.
                # The data is already loaded in every worker's memory.
                future = executor.submit(
                    train_and_evaluate, C, i
                )
                all_futures[future] = i
            
            # Process results as they complete
            for i, future in enumerate(as_completed(all_futures)):
                try:
                    C, acc, trial_id = future.result()
                    
                    print(
                        f"{trial_id:02d}: C={C:.3e}, acc={acc:.4f}"
                    )
                    results.append((C, acc))
                except Exception as e:
                    print(f"Trial {all_futures[future]:02d} failed with error: {e}")
                    
            # --- Timing End and Calculation ---
                
            # -----------------------------
            # 4. Best C
            # -----------------------------
            if results:
                best_C, best_acc = max(results, key=lambda t: t[1])
                print("\n--- Best result ---")
                print(f"C={best_C:.3e}, acc={best_acc:.4f}")
            else:
                print("\nNo results found.")

            print(f"{time.time()-start}s")
